apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
  labels:
    app: promtail
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://loki:3100/loki/api/v1/push
    scrape_configs:
      - job_name: brute-force-pods
        static_configs:
          - targets:
              - localhost
            labels:
              job: kubernetes-pods
              __path__: /var/log/pods/*/*/*.log
        pipeline_stages:
          - regex:
              source: filename
              # On cherche spécifiquement ce qui est APRES /var/log/pods/ et AVANT le premier underscore _
              expression: "/var/log/pods/(?P<namespace>[^/_]+)_(?P<pod>[^_]+)_[^/]+/(?P<container>[^/]+)/.*\\.log"
          - labels:
              namespace:
              pod:
              container:
          - template:
              source: app
              template: '{{ .container }}'
          - labels:
              app:
          - docker: {}