# k8s/mlflow/mlflow-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: cloudpredict
  labels:
    app: cloudpredict
    component: mlflow
spec:
  type: NodePort
  selector:
    component: mlflow  # On enlève "app: cloudpredict" ici
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500