apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  namespace: cloudpredict
  labels:
    app: mlflow
    component: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mlflow
  template:
    metadata:
      labels:
        component: mlflow
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
      - name: mlflow-server
        image: ghcr.io/mlflow/mlflow:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: cloudpredict-config
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: cloudpredict-config
              key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudpredict-secret
              key: POSTGRES_PASSWORD
        # Construction de l'URI de connexion SQLAlchemy
        - name: MLFLOW_BACKEND_STORE_URI
          value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-service:5432/$(POSTGRES_DB)
        - name: MLFLOW_ARTIFACT_ROOT
          value: /mlflow/artifacts
        # Écrase la commande par défaut pour installer le driver manquant avant de lancer le serveur
        command: ["/bin/sh", "-c"]
        args:
        - |
          pip install psycopg2-binary
          mlflow server \
            --host=0.0.0.0 \
            --port=5000 \
            --backend-store-uri=${MLFLOW_BACKEND_STORE_URI} \
            --default-artifact-root mlflow-artifacts:/ --artifacts-destination ${MLFLOW_ARTIFACT_ROOT}
        volumeMounts:
        - name: mlflow-storage
          mountPath: /mlflow
      volumes:
      - name: mlflow-storage
        persistentVolumeClaim:
          claimName: mlflow-pvc